// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.il.facade;

public final class LoanServiceImpl_Stub
    extends java.rmi.server.RemoteStub
    implements com.il.facade.LoanService
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("com.il.dto.LoanDetails applyLoan(com.il.dto.LoanApplication)")
    };
    
    private static final long interfaceHash = 1480879776180184475L;
    
    // constructors
    public LoanServiceImpl_Stub() {
	super();
    }
    public LoanServiceImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of applyLoan(LoanApplication)
    public com.il.dto.LoanDetails applyLoan(com.il.dto.LoanApplication $param_LoanApplication_1)
	throws java.rmi.RemoteException
    {
	try {
	    java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 0, interfaceHash);
	    try {
		java.io.ObjectOutput out = call.getOutputStream();
		out.writeObject($param_LoanApplication_1);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling arguments", e);
	    }
	    ref.invoke(call);
	    com.il.dto.LoanDetails $result;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$result = (com.il.dto.LoanDetails) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling return", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling return", e);
	    } finally {
		ref.done(call);
	    }
	    return $result;
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
