// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.il.facade;

public final class LoanServiceImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("com.il.dto.LoanDetails applyLoan(com.il.dto.LoanApplication)")
    };
    
    private static final long interfaceHash = 1480879776180184475L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (hash != interfaceHash)
	    throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	
	com.il.facade.LoanServiceImpl server = (com.il.facade.LoanServiceImpl) obj;
	switch (opnum) {
	case 0: // applyLoan(LoanApplication)
	{
	    com.il.dto.LoanApplication $param_LoanApplication_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_LoanApplication_1 = (com.il.dto.LoanApplication) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    com.il.dto.LoanDetails $result = server.applyLoan($param_LoanApplication_1);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
