//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 06:06:43 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.stackspace.org/webfaces/config-2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.stackspace.webfaces.config2;
