//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 06:06:43 PM IST 
//


package org.stackspace.webfaces.config2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for web-faces complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="web-faces">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="global-forwards" type="{http://www.stackspace.org/webfaces/config-2.0}global-forwards"/>
 *         &lt;element name="command-configs" type="{http://www.stackspace.org/webfaces/config-2.0}command-configs"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "web-faces", propOrder = {
    "globalForwards",
    "commandConfigs"
})
public class WebFaces {

    @XmlElement(name = "global-forwards", required = true)
    protected GlobalForwards globalForwards;
    @XmlElement(name = "command-configs", required = true)
    protected CommandConfigs commandConfigs;

    /**
     * Gets the value of the globalForwards property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalForwards }
     *     
     */
    public GlobalForwards getGlobalForwards() {
        return globalForwards;
    }

    /**
     * Sets the value of the globalForwards property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalForwards }
     *     
     */
    public void setGlobalForwards(GlobalForwards value) {
        this.globalForwards = value;
    }

    /**
     * Gets the value of the commandConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link CommandConfigs }
     *     
     */
    public CommandConfigs getCommandConfigs() {
        return commandConfigs;
    }

    /**
     * Sets the value of the commandConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandConfigs }
     *     
     */
    public void setCommandConfigs(CommandConfigs value) {
        this.commandConfigs = value;
    }

}
